# Exercice 1 : trouver les antécédents

### Code fourni
/!\ ne pas modifier /!\

Import du package "Numpy" pour avoir accès au produit matriciel et produit matrice/vecteur

In [22]:
import numpy as np

Les matrices et leur images qui serviront pour les tests (pour chaque cas : deux matrices 3x3 et une matrice 4x4)

In [23]:
matrices_diag = []
matrices_diag.append(np.array([[ 4.2, 0, 0 ],[0, 1.4, 0], [0, 0, 2.3]]))
matrices_diag.append(np.array([[ -1.6, 0, 0 ],[0, 8.1, 0], [0, 0, -3.1]]))
matrices_diag.append(np.array([[ -7.1, 0, 0, 0 ],[0, 6.8, 0, 0], [0, 0, -2.1, 0], [0, 0, 0, 9.1]]))

matrices_sup = []
matrices_sup.append(np.array([[ 4.2, 1.1, 7.3 ],[0, 1.4, 2.4], [ 0, 0, 2.3]]))
matrices_sup.append(np.array([[ 1.1, -6.7, 9.3 ],[0, -4.3, 0.2], [ 0, 0, -3.4]]))
matrices_sup.append(np.array([[ 5.7, 5.6, -5.3, 6.0 ],[ 0, -1.6, 4.7, 1.5], [0, 0, -7.3, 3.2], [0, 0, 0, 1.8]]))

matrices_inf = []
matrices_inf.append(np.array([[ 6.6, 0, 0 ],[ 0.1, 1.2, 0], [ 5.6, 5.9, 9.0 ]]))
matrices_inf.append(np.array([[ 7.7, 0, 0 ], [ 4.1, 3.3, 0 ], [ 3.1, 5.3, 6.9]]))
matrices_inf.append(np.array([[ -1.9, 0, 0, 0 ],[5.2, 8.9, 0, 0], [-7.9, 3.6, -9.8, 0], [8.4, -1.5, -7.6, 0.9]]))

matrices = []
matrices.append( np.array([[ 3.6, 2.1, 5.5 ],[1.7, 1.3, 2.4], [ 7.1, 6.8, 2.3]]) )
matrices.append( np.array([[ 2.2, 4.1, 1.9 ], [ -1.7, -3.0, 1.6 ], [ 4.5, -7.4, 2.1 ]]) )
matrices.append(np.array([[ -0.7, 6.0, -9.1, 4.2 ],[4.2, 2.8, -4.7, 3.9], [-2.5, 4.3, -9.3, 3.9], [-5.7, 2.0, 5.3, -9.9]]))

images = []
images.append(np.array([ 4.2, 1.4, 2.3 ]))
images.append(np.array([ 0.4, -1.5, 1.6 ]))
images.append(np.array([ 0.7, -6.0, -5.7, 1.6 ]))

Les fonctions de test

In [24]:
def test ( fonction, A, b ) :
    x = fonction ( np.copy(A), np.copy(b) )
    res = np.dot ( A, x )
    print ( b )
    erreur = 0
    for i in range ( len(b) ) :
        erreur += abs ( res[i]-b[i] )
    if ( erreur < 0.0001 ) :
        print ( "    =" )
    else :
        print ( "    !=" )
    print ( A )
    print ( "    *" )
    print ( x )   
    print()  

def test_multiple ( fonction, liste_matrices, listes_images ) :
    for i in range ( len ( liste_matrices ) ) :
        print ( "Test numéro", (i+1), ":\n" )
        test ( fonction, liste_matrices[i], listes_images[i] )

## Question 1 : matrices diagonales

In [25]:
def resolution_diagonale ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Diagonale *****\n")
test_multiple ( resolution_diagonale, matrices_diag, images )

***** Diagonale *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[4.2 0.  0. ]
 [0.  1.4 0. ]
 [0.  0.  2.3]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[-1.6  0.   0. ]
 [ 0.   8.1  0. ]
 [ 0.   0.  -3.1]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7  1.6]
    !=
[[-7.1  0.   0.   0. ]
 [ 0.   6.8  0.   0. ]
 [ 0.   0.  -2.1  0. ]
 [ 0.   0.   0.   9.1]]
    *
[0. 0. 0. 0.]



## Question 2a : matrices triangulaires inférieures

In [26]:
def resolution_inferieure ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Triangulaire inférieure *****\n")
test_multiple ( resolution_inferieure, matrices_inf, images )

***** Triangulaire inférieure *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[6.6 0.  0. ]
 [0.1 1.2 0. ]
 [5.6 5.9 9. ]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[7.7 0.  0. ]
 [4.1 3.3 0. ]
 [3.1 5.3 6.9]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7  1.6]
    !=
[[-1.9  0.   0.   0. ]
 [ 5.2  8.9  0.   0. ]
 [-7.9  3.6 -9.8  0. ]
 [ 8.4 -1.5 -7.6  0.9]]
    *
[0. 0. 0. 0.]



## Question 2b : matrices triangulaires supérieures

In [27]:
def resolution_superieure ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Triangulaire supérieure *****\n")
test_multiple ( resolution_superieure, matrices_sup, images )

***** Triangulaire supérieure *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[4.2 1.1 7.3]
 [0.  1.4 2.4]
 [0.  0.  2.3]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[ 1.1 -6.7  9.3]
 [ 0.  -4.3  0.2]
 [ 0.   0.  -3.4]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7  1.6]
    !=
[[ 5.7  5.6 -5.3  6. ]
 [ 0.  -1.6  4.7  1.5]
 [ 0.   0.  -7.3  3.2]
 [ 0.   0.   0.   1.8]]
    *
[0. 0. 0. 0.]



## Question 3 : résolution de Gauss

In [28]:
def resolution_gauss ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Pivot de Gauss *****\n")
test_multiple ( resolution_gauss, matrices, images )

***** Pivot de Gauss *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[3.6 2.1 5.5]
 [1.7 1.3 2.4]
 [7.1 6.8 2.3]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[ 2.2  4.1  1.9]
 [-1.7 -3.   1.6]
 [ 4.5 -7.4  2.1]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7  1.6]
    !=
[[-0.7  6.  -9.1  4.2]
 [ 4.2  2.8 -4.7  3.9]
 [-2.5  4.3 -9.3  3.9]
 [-5.7  2.   5.3 -9.9]]
    *
[0. 0. 0. 0.]



## Question 4 : résolution lower-upper

In [29]:
def resolution_LU ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Méthode LU *****\n")
test_multiple ( resolution_LU, matrices, images )

***** Méthode LU *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[3.6 2.1 5.5]
 [1.7 1.3 2.4]
 [7.1 6.8 2.3]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[ 2.2  4.1  1.9]
 [-1.7 -3.   1.6]
 [ 4.5 -7.4  2.1]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7  1.6]
    !=
[[-0.7  6.  -9.1  4.2]
 [ 4.2  2.8 -4.7  3.9]
 [-2.5  4.3 -9.3  3.9]
 [-5.7  2.   5.3 -9.9]]
    *
[0. 0. 0. 0.]



# Exercice 2 : inversion de matrices

### Code fourni
/!\ ne pas modifier /!\

Import du package "Numpy" pour avoir accès au produit matriciel et produit matrice/vecteur

In [30]:
import numpy as np

Les matrices qui serviront pour les tests (pour chaque cas : deux matrices 3x3 et une matrice 4x4)

In [31]:
matrices_diag = []
matrices_diag.append(np.array([[ 4.2, 0, 0 ],[0, 1.4, 0], [0, 0, 2.3]]))
matrices_diag.append(np.array([[ -1.6, 0, 0 ],[0, 8.1, 0], [0, 0, -3.1]]))
matrices_diag.append(np.array([[ -7.1, 0, 0, 0 ],[0, 6.8, 0, 0], [0, 0, -2.1, 0], [0, 0, 0, 9.1]]))

matrices_sup = []
matrices_sup.append(np.array([[ 4.2, 1.1, 7.3 ],[0, 1.4, 2.4], [ 0, 0, 2.3]]))
matrices_sup.append(np.array([[ 1.1, -6.7, 9.3 ],[0, -4.3, 0.2], [ 0, 0, -3.4]]))
matrices_sup.append(np.array([[ 5.7, 5.6, -5.3, 6.0 ],[ 0, -1.6, 4.7, 1.5], [0, 0, -7.3, 3.2], [0, 0, 0, 1.8]]))

matrices_inf = []
matrices_inf.append(np.array([[ 6.6, 0, 0 ],[ 0.1, 1.2, 0], [ 5.6, 5.9, 9.0 ]]))
matrices_inf.append(np.array([[ 7.7, 0, 0 ], [ 4.1, 3.3, 0 ], [ 3.1, 5.3, 6.9]]))
matrices_inf.append(np.array([[ -1.9, 0, 0, 0 ],[5.2, 8.9, 0, 0], [-7.9, 3.6, -9.8, 0], [8.4, -1.5, -7.6, 0.9]]))

matrices = []
matrices.append( np.array([[ 3.6, 2.1, 5.5 ],[1.7, 1.3, 2.4], [ 7.1, 6.8, 2.3]]) )
matrices.append( np.array([[ 2.2, 4.1, 1.9 ], [ -1.7, -3.0, 1.6 ], [ 4.5, -7.4, 2.1 ]]) )
matrices.append(np.array([[ -0.7, 6.0, -9.1, 4.2 ],[4.2, 2.8, -4.7, 3.9], [-2.5, 4.3, -9.3, 3.9], [-5.7, 2.0, 5.3, -9.9]]))


Les fonctions de test

In [32]:
def test ( fonction, A ) :
    inv = fonction ( np.copy(A) )
    res = np.dot ( A, inv )
    eye = np.eye ( len(A) )
    print ( eye )
    erreur = 0
    for i in range ( len(A) ) :
        for j in range ( len (A) ) :
            erreur += abs ( eye[i][j]-res[i][j] )
    if ( erreur < 0.0001 ) :
        print ( "    =" )
    else :
        print ( "    !=" )
    print ( A )
    print ( "    *" )
    print ( inv )   
    print()  

def test_multiple ( fonction, liste_matrices ) :
    for i in range ( len ( liste_matrices ) ) :
        print ( "Test numéro", (i+1), ":\n" )
        test ( fonction, liste_matrices[i] )

## Question 1 : matrices diagonales

In [33]:
def inversion_diagonale ( A ) :
    inv = np.zeros((len(A), len(A)))
    # Ajoutez ici le calcul de la matrice inverse
    return inv

print("***** Diagonale *****\n")
test_multiple ( inversion_diagonale, matrices_diag )

***** Diagonale *****

Test numéro 1 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[4.2 0.  0. ]
 [0.  1.4 0. ]
 [0.  0.  2.3]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 2 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[-1.6  0.   0. ]
 [ 0.   8.1  0. ]
 [ 0.   0.  -3.1]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 3 :

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
    !=
[[-7.1  0.   0.   0. ]
 [ 0.   6.8  0.   0. ]
 [ 0.   0.  -2.1  0. ]
 [ 0.   0.   0.   9.1]]
    *
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



## Question 2a : matrices triangulaires inférieures

In [34]:
def inversion_inferieure ( A ) :
    inv = np.zeros((len(A), len(A)))
    # Ajoutez ici le calcul de la matrice inverse
    return inv

print("***** Triangulaires inférieures *****\n")
test_multiple ( inversion_inferieure, matrices_inf )

***** Triangulaires inférieures *****

Test numéro 1 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[6.6 0.  0. ]
 [0.1 1.2 0. ]
 [5.6 5.9 9. ]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 2 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[7.7 0.  0. ]
 [4.1 3.3 0. ]
 [3.1 5.3 6.9]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 3 :

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
    !=
[[-1.9  0.   0.   0. ]
 [ 5.2  8.9  0.   0. ]
 [-7.9  3.6 -9.8  0. ]
 [ 8.4 -1.5 -7.6  0.9]]
    *
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



## Question 2b : matrices triangulaires supérieures

In [35]:
def inversion_superieure ( A ) :
    inv = np.zeros((len(A), len(A)))
    # Ajoutez ici le calcul de la matrice inverse
    return inv

print("***** Triangulaires supérieures *****\n")
test_multiple ( inversion_superieure, matrices_sup )

***** Triangulaires supérieures *****

Test numéro 1 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[4.2 1.1 7.3]
 [0.  1.4 2.4]
 [0.  0.  2.3]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 2 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[ 1.1 -6.7  9.3]
 [ 0.  -4.3  0.2]
 [ 0.   0.  -3.4]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 3 :

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
    !=
[[ 5.7  5.6 -5.3  6. ]
 [ 0.  -1.6  4.7  1.5]
 [ 0.   0.  -7.3  3.2]
 [ 0.   0.   0.   1.8]]
    *
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



## Question 3 : méthode du pivot de Gauss

In [36]:
def inversion_gauss ( A ) :
    inv = np.zeros((len(A), len(A)))
    # Ajoutez ici le calcul de la matrice inverse
    return inv

print("***** Pivot de Gauss *****\n")
test_multiple ( inversion_gauss, matrices )

***** Pivot de Gauss *****

Test numéro 1 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[3.6 2.1 5.5]
 [1.7 1.3 2.4]
 [7.1 6.8 2.3]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 2 :

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
    !=
[[ 2.2  4.1  1.9]
 [-1.7 -3.   1.6]
 [ 4.5 -7.4  2.1]]
    *
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Test numéro 3 :

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
    !=
[[-0.7  6.  -9.1  4.2]
 [ 4.2  2.8 -4.7  3.9]
 [-2.5  4.3 -9.3  3.9]
 [-5.7  2.   5.3 -9.9]]
    *
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



# Exercice 3 : méthodes itératives

### Code fourni
/!\ ne pas modifier /!\

Import du package "Numpy" pour avoir accès au produit matriciel et produit matrice/vecteur

In [37]:
import numpy as np

Les matrices et leur images qui serviront pour les tests (trois matrices 3x3)

In [38]:
matrices = []
matrices.append( np.array([[ 2.0, 1.0, 0.0 ], [ 1.0, 3.0, 1.0 ], [ 1.0, 1.0, 3.0 ]]) )
matrices.append( np.array([[ 0.6, -0.3, 0.1 ],[ -0.1, 0.4, 0.3 ], [ -0.2, 0.1, -0.5 ]]) )
matrices.append(np.array([ [ 5.0, 2.0, -1.0 ],[ 1.0, 6.0, -3.0 ], [ 2.0, 1.0, 4.0 ] ]))

images = []
images.append(np.array([ 4.2, 1.4, 2.3 ]))
images.append(np.array([ 0.4, -1.5, 1.6 ]))
images.append(np.array([ 0.7, -6.0, -5.7 ]))


Les fonctions de test

In [39]:
def test ( fonction, A, b ) :
    x = fonction ( np.copy(A), np.copy(b) )
    res = np.dot ( A, x )
    print ( b )
    erreur = 0
    for i in range ( len(b) ) :
        erreur += abs ( res[i]-b[i] )
    if ( erreur < 0.0001 ) :
        print ( "    =" )
    else :
        print ( "    !=" )
    print ( A )
    print ( "    *" )
    print ( x )   
    print()  

def test_multiple ( fonction, liste_matrices, listes_images ) :
    for i in range ( len ( liste_matrices ) ) :
        print ( "Test numéro", (i+1), ":\n" )
        test ( fonction, liste_matrices[i], listes_images[i] )

## Question 1 : algorithme itératif

In [43]:
def resolution_iterative ( inv_M, N, b ) :
    antecedent = np.array([0.0]*len(b))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

## Question 2 : résolution de Jacobi

In [44]:
def resolution_jacobi ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Jacobi *****\n")
test_multiple ( resolution_jacobi, matrices, images )

***** Jacobi *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[2. 1. 0.]
 [1. 3. 1.]
 [1. 1. 3.]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[ 0.6 -0.3  0.1]
 [-0.1  0.4  0.3]
 [-0.2  0.1 -0.5]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7]
    !=
[[ 5.  2. -1.]
 [ 1.  6. -3.]
 [ 2.  1.  4.]]
    *
[0. 0. 0.]



## Question 3 : résolution de Gauss-Siedel

In [42]:
def resolution_gauss_siedel ( A, b ) :
    antecedent = np.array([0.0]*len(A))
    # Ajoutez ici le calcul de l'antécédent
    return antecedent

print("***** Gauss-Siedel *****\n")
test_multiple ( resolution_gauss_siedel, matrices, images )

***** Gauss-Siedel *****

Test numéro 1 :

[4.2 1.4 2.3]
    !=
[[2. 1. 0.]
 [1. 3. 1.]
 [1. 1. 3.]]
    *
[0. 0. 0.]

Test numéro 2 :

[ 0.4 -1.5  1.6]
    !=
[[ 0.6 -0.3  0.1]
 [-0.1  0.4  0.3]
 [-0.2  0.1 -0.5]]
    *
[0. 0. 0.]

Test numéro 3 :

[ 0.7 -6.  -5.7]
    !=
[[ 5.  2. -1.]
 [ 1.  6. -3.]
 [ 2.  1.  4.]]
    *
[0. 0. 0.]

